CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" string NOT NULL,
  "email" string UNIQUE NOT NULL,
  "password" string,
  "uid" string NOT NULL,
  "image" string,
  "cover" string,
  "profile" string,
  "address" string,
  "kink" string,
  "birth" string,
  "fixed_posts" integer,
  "created_at" datetime
);

CREATE TABLE "follow" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "follow_user" integer NOT NULL,
  "following_user" integer NOT NULL
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "body" string NOT NULL,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "quote_posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "post_id" integer NOT NULL,
  "body" string NOT NULL,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" string NOT NULL,
  "type_id" tinyint
);

CREATE TABLE "posts_media" (
  "post_id" integer NOT NULL,
  "media_id" integer NOT NULL
);

CREATE TABLE "likes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "post_id" integer NOT NULL
);

CREATE TABLE "reply" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" integer NOT NULL,
  "detail" string NOT NULL,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "repost" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "post_id" integer NOT NULL
);

CREATE TABLE "bookmarks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "post_id" integer NOT NULL
);

CREATE TABLE "mutes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "muteing_user" integer NOT NULL,
  "muted_user" integer NOT NULL
);

CREATE UNIQUE INDEX ON "follow" ("follow_user", "following_user");

CREATE UNIQUE INDEX ON "mutes" ("muteing_user", "muted_user");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("fixed_posts") REFERENCES "posts" ("id");

ALTER TABLE "posts_media" ADD FOREIGN KEY ("media_id") REFERENCES "media" ("id");

ALTER TABLE "posts_media" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "reply" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "repost" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "repost" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "quote_posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "quote_posts" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "bookmarks" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "bookmarks" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "follow" ADD FOREIGN KEY ("follow_user") REFERENCES "users" ("id");

ALTER TABLE "follow" ADD FOREIGN KEY ("following_user") REFERENCES "users" ("id");

ALTER TABLE "mutes" ADD FOREIGN KEY ("muteing_user") REFERENCES "users" ("id");

ALTER TABLE "mutes" ADD FOREIGN KEY ("muted_user") REFERENCES "users" ("id");
