CREATE TABLE "media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer NOT NULL,
  "created_at" datetime NOT NULL,
  "updated_at" datetime NOT NULL
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" string NOT NULL,
  "email" string UNIQUE NOT NULL,
  "password" string NOT NULL,
  "created_at" datetime NOT NULL,
  "updated_at" datetime NOT NULL
);

CREATE TABLE "subscribe" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "subscribe_user" integer NOT NULL,
  "subscribed_user" integer NOT NULL
);

CREATE TABLE "like" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer NOT NULL,
  "media_id" integer NOT NULL
);

CREATE TABLE "watched_media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer NOT NULL,
  "media_id" integer NOT NULL
);

CREATE TABLE "coments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer NOT NULL,
  "media_id" integer NOT NULL,
  "detail" string NOT NULL,
  "created_at" datetime NOT NULL,
  "updated_at" datetime NOT NULL
);

CREATE UNIQUE INDEX ON "subscribe" ("subscribe_user", "subscribed_user");

CREATE UNIQUE INDEX ON "like" ("user_id", "media_id");

ALTER TABLE "media" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "subscribe" ADD FOREIGN KEY ("subscribe_user") REFERENCES "users" ("id");

ALTER TABLE "subscribe" ADD FOREIGN KEY ("subscribed_user") REFERENCES "users" ("id");

ALTER TABLE "like" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "like" ADD FOREIGN KEY ("media_id") REFERENCES "media" ("id");

ALTER TABLE "watched_media" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "watched_media" ADD FOREIGN KEY ("media_id") REFERENCES "media" ("id");

ALTER TABLE "coments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "coments" ADD FOREIGN KEY ("media_id") REFERENCES "media" ("id");
