CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" string NOT NULL,
  "email" string UNIQUE NOT NULL,
  "password" string NOT NULL,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "memos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "content" string NOT NULL,
  "created_at" datetime,
  "deleted_at" datetime DEFAULT null,
  "updated_at" datetime
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "name" string NOT NULL,
  "created_at" datetime
);

CREATE TABLE "memo_tags" (
  "memo_id" interger,
  "tag_id" interger
);

ALTER TABLE "memos" ADD FOREIGN KEY ("content") REFERENCES "users" ("id");

ALTER TABLE "memo_tags" ADD FOREIGN KEY ("memo_id") REFERENCES "tags" ("name");

ALTER TABLE "memo_tags" ADD FOREIGN KEY ("memo_id") REFERENCES "memos" ("created_at");
